### ISSUE TITLE
Make XML names case insensitive

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-project-loader#6]
For historical reasons, element and attribute names in the project format are a mix of UpperCamelCase, lowerCamelCase and lowercase. See: https://github.com/nunit/docs/wiki/NUnit-Project-XML-Format

This has caused a couple of issues: https://github.com/nunit/nunit/issues/1893 https://github.com/nunit/docs/issues/80. 

Making xml elements case-insensitive isn't an ideal solution, but I feel like it would be an improvement over the current situation. What do people think?

**Comment by ChrisMaddock** [comment]
Another option: standardise everything e.g. as lowercase, and have the project loader accept either lowercase or relevantOldCasing for each individual attribute.

**Comment by CharliePoole** [comment]
I think this is a bad idea...

Unlike HTML, XML does not have a notion of case-insensitive element or attribute names. The names we use are - as you say - slightly inconsistent, but they have never been changed since the format was invented so there is no backward-compatibility issue. Over all this time, the casing has not caused a problem. Fairly recently, I created documentation for the format, which contained a few errors.  That's where this comes from. So, let's just fix the docs - that's done - and not feel we have to change the XML format to match them.

Over the years, we have always advised users - especially newbies - that they should __not__ be trying to type in the XML for a project file. There are much more subtle problems when you do that than getting the spelling of the attributes right. Knowing where to use an absolute and where to use a relative path is quite important. We have a program, the project editor, which knows all the rules and creates the XML in correct format. It seems to me that we may have stopped reminding people about its existence.

Finally, the nunit project format may well be a legacy format, which makes it particularly silly to start fooling around with it. The format does not support many things that we can do now, such as having packages contain other packages. At some point, we will probably want to create a new format and start phasing out the old one.

If we do create a new format, we should aim for a much greater degree of consistency in naming. Camel-case turns out to be a bad idea in many instances, because people do not always agree on whether a particular name is one word or several. SetUp versus Setup comes to mind. :-)

**Comment by ChrisMaddock** [comment]
Ok, I'll take those points. :-)

I wasn't aware the xml format wasn't designed to be edited by hand - that would always be my preference for editing a small xml file, over using a GUI to do the same. Likewise, I wasn't aware `.nunit` was intended to be legacy - if we're fixing the problem with a better format - that sounds good to me!

**Comment by CharliePoole** [comment]
To be clear, I think we need a better format, but it will be up to you guys to decide whether to do it.

Currently, most people using nunit projects seem to get them via TeamCity's generation of them.

I agree with your approach to using an editor. But you're an experienced developer who knows that spelling counts in XML. So many of our users these days are either low-experience or not programmers at all, which seems to lead to problems. I'd rather those guys use the gui.

**Comment by ChrisMaddock** [comment]
I'm just going to close this one, if I'm the first person to bring it up in 10 years, I guess it can't be so important!

**Comment by CharliePoole** [comment]
@ChrisMaddock No problem that you bring it up. It's good to keep stuff like this in mind as we do newer things... maybe we should even have some naming standard for future XML.

But when a project lasts as long as this one has, with its significant emphasis on backward compatibility, you want to be very careful about what you change. We did a bunch of breaking changes for 3.0, of course, but that was announced way in advance and I'd expect it to be a rare event.

Deciding the ongoing balance between compatibility and new changes is one of the key jobs I hope the Core Team will take on. I'll send out something about that soon.
